#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
sudo apt update 
sudo apt install nginx 
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
